### ISSUE TITLE
`KeyError: '4ee6ccd4_modbus_inverter'` in logs when trying to install add-on

### ISSUE THREAD

**Issue by bjeanes** [TenySmart/ModbusTCP2MQTT#41]
```
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 106, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 181, in install
    await addon.instance.install(store.version, store.image, arch=addon.arch)
  File "/usr/src/supervisor/supervisor/utils/__init__.py", line 33, in wrap_api
    return await method(api, *args, **kwargs)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 534, in _install
    self._build(version)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 560, in _build
    _LOGGER.error("Can't build %s:%s: %s", self.image, version, err)
  File "/usr/src/supervisor/supervisor/docker/addon.py", line 78, in image
    return self.addon.image
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 391, in image
    return self.persist.get(ATTR_IMAGE)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 165, in persist
    return self.sys_addons.data.user[self.slug]
KeyError: '4ee6ccd4_modbus_inverter'
```

**Comment by bjeanes** [comment]
Retrying a few times and eventually it installed...
